DWAPlannerROS:
  max_vel_x: 0.6
  min_vel_x: 0.1
  max_vel_theta: 1.0
  min_vel_theta: 0.2
  acc_lim_theta: 3.2
  acc_lim_x: 2.5
  acc_lim_y: 0.0
  xy_goal_tolerance: 0.2
  yaw_goal_tolerance: 0.2
  latch_xy_goal_tolerance: true
  prune_plan: true
