global_costmap:
  global_frame: "map"
  robot_base_frame: "base_link"
  update_frequency: 10.0
  publish_frequency: 0.5
  static_map: true
  transform_tolerance: 0.05
  resolution: 0.05
  rolling_window: false
  width: 20.0
  height: 20.0
