image: /home/belabed/DRL-robot-navigation/catkin_ws/src/multi_robot_scenario/map/my_map.pgm
resolution: 0.100000
origin: [-5.500000, -5.500000, 0.000000]
negate: 0
occupied_thresh: 0.65
free_thresh: 0.196

